export default {
    GET_ERRORS: 'GET_ERRORS',
    SET_MENU_BAR : 'SET_MENU_BAR',
    SET_CANCEL : 'SET_CANCEL',
    SET_JOB_OBJECT : 'SET_JOB_OBJECT',
    SET_CAR_OBJECT : 'SET_CAR_OBJECT',
    SET_ROOM_OBJECT : 'SET_ROOM_OBJECT'
}