export default {
    GET_ERRORS: 'GET_ERRORS',
    SET_MENU_BAR : 'SET_MENU_BAR',
    SET_CANCEL : 'SET_CANCEL',
    SET_JOB_OBJECT : 'SET_JOB_OBJECT',
    SET_CAR_0R_ROOM_OBJECT : 'SET_CAR_OR_ROOM_OBJECT',
}